"""empty message

Revision ID: 5314cde0aa04
Revises: None
Create Date: 2014-03-27 12:38:19.545190

"""

# revision identifiers, used by Alembic.
revision = '5314cde0aa04'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brickconfig',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('app_version', sa.String(length=36), nullable=True),
    sa.Column('minimum_requirement', sa.String(length=36), nullable=True),
    sa.Column('ports', sa.Text(), nullable=True),
    sa.Column('environ', sa.Text(), nullable=True),
    sa.Column('email_template', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid', name='uniq_brickconfig0uuid')
    )
    op.create_table('brick',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('brickconfig_uuid', sa.String(length=36), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('instance_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=36), nullable=True),
    sa.Column('configuration', sa.Text(), nullable=True),
    sa.Column('deploy_log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid', name='uniq_brick0uuid')
    )
    op.create_index('brick_config_uuid', 'brick', ['brickconfig_uuid'], unique=False)
    op.create_index('brick_instance_uuid', 'brick', ['instance_id'], unique=False)
    op.create_index('brick_tenant_id', 'brick', ['tenant_id'], unique=False)
    op.create_table('brickconfig_file',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('brickconfig_uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contents', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid', name='uniq_configfile0uuid')
    )
    op.create_index('configfile_brickconfig_uuid', 'brickconfig_file', ['brickconfig_uuid'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('configfile_brickconfig_uuid', table_name='brickconfig_file')
    op.drop_table('brickconfig_file')
    op.drop_index('brick_tenant_id', table_name='brick')
    op.drop_index('brick_instance_uuid', table_name='brick')
    op.drop_index('brick_config_uuid', table_name='brick')
    op.drop_table('brick')
    op.drop_table('brickconfig')
    ### end Alembic commands ###
