"""empty message

Revision ID: ebdc3c27e82
Revises: 4307e329ce2e
Create Date: 2014-04-14 14:08:00.293431

"""

# revision identifiers, used by Alembic.
revision = 'ebdc3c27e82'
down_revision = '4307e329ce2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brick', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.create_index('brick_deleted', 'brick', ['deleted'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('brick_deleted', table_name='brick')
    op.drop_column('brick', 'deleted')
    ### end Alembic commands ###
